-- SSHP production database for MySQL 8 / MariaDB 10.5+.
CREATE TABLE IF NOT EXISTS users (id VARCHAR(64) PRIMARY KEY, username VARCHAR(190) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL DEFAULT 'admin', status VARCHAR(30) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS service_requests (id VARCHAR(64) PRIMARY KEY, service VARCHAR(190) NOT NULL, name VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, email VARCHAR(190) NULL, requirement TEXT NOT NULL, action VARCHAR(30) NULL, status VARCHAR(50) NOT NULL DEFAULT 'received', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_sr_created(created_at), INDEX idx_sr_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS teacher_interests (id VARCHAR(64) PRIMARY KEY, name VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, qualification VARCHAR(190) NOT NULL, subject VARCHAR(190) NOT NULL, opportunity VARCHAR(100) NOT NULL, details TEXT NULL, status VARCHAR(50) NOT NULL DEFAULT 'received', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_ti_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS school_requirements (id VARCHAR(64) PRIMARY KEY, school VARCHAR(190) NOT NULL, contact VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, location VARCHAR(190) NOT NULL, type VARCHAR(100) NOT NULL, details TEXT NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'received', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_scr_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS content_submissions (id VARCHAR(64) PRIMARY KEY, title VARCHAR(255) NULL, category VARCHAR(100) NULL, description TEXT NULL, name VARCHAR(190) NULL, email VARCHAR(190) NULL, phone VARCHAR(50) NULL, status VARCHAR(50) NOT NULL DEFAULT 'received', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_cs_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS submissions (id VARCHAR(64) PRIMARY KEY, type VARCHAR(190) NOT NULL, data JSON NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'received', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_sub_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS resources (id VARCHAR(64) PRIMARY KEY, title VARCHAR(255) NOT NULL, category VARCHAR(100) NULL, description TEXT NULL, status VARCHAR(50) NOT NULL DEFAULT 'published', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_res_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS announcements (id VARCHAR(64) PRIMARY KEY, title VARCHAR(255) NOT NULL, category VARCHAR(100) NULL, description TEXT NULL, status VARCHAR(50) NOT NULL DEFAULT 'published', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_ann_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS quotes (id VARCHAR(64) PRIMARY KEY, service_request_id VARCHAR(64) NULL, customer_name VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, email VARCHAR(190) NULL, service VARCHAR(190) NOT NULL, amount_minor BIGINT NULL, currency CHAR(3) DEFAULT 'PKR', notes TEXT NULL, status VARCHAR(50) NOT NULL DEFAULT 'requested', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_q_created(created_at), INDEX idx_q_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders (id VARCHAR(64) PRIMARY KEY, quote_id VARCHAR(64) NULL, customer_name VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, email VARCHAR(190) NULL, service VARCHAR(190) NOT NULL, amount_minor BIGINT NULL, currency CHAR(3) DEFAULT 'PKR', status VARCHAR(50) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_o_created(created_at), INDEX idx_o_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payments (id VARCHAR(64) PRIMARY KEY, order_id VARCHAR(64) NOT NULL, method VARCHAR(20) NOT NULL DEFAULT 'omni', transaction_reference VARCHAR(190) NOT NULL, sender_name VARCHAR(190) NOT NULL, sender_phone VARCHAR(50) NOT NULL, amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'PKR', status VARCHAR(50) NOT NULL DEFAULT 'pending_verification', notes TEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NULL, INDEX idx_p_order(order_id), INDEX idx_p_status(status), INDEX idx_p_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notifications (id VARCHAR(64) PRIMARY KEY, type VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, recipient VARCHAR(190) NOT NULL, entity_id VARCHAR(64) NULL, read_flag TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, INDEX idx_n_created(created_at), INDEX idx_n_read(read_flag)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sessions (id CHAR(64) PRIMARY KEY, username VARCHAR(190) NOT NULL, role VARCHAR(30) NOT NULL, expires_at BIGINT NOT NULL, created_at DATETIME NOT NULL, INDEX idx_s_expiry(expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_log (id VARCHAR(64) PRIMARY KEY, action VARCHAR(190) NOT NULL, entity_id VARCHAR(64) NULL, type VARCHAR(100) NULL, actor VARCHAR(190) NULL, metadata JSON NULL, created_at DATETIME NOT NULL, INDEX idx_a_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
