document.addEventListener("DOMContentLoaded", () => {
  const toggle=document.querySelector(".menu-toggle"), nav=document.querySelector(".main-nav"), sidebar=document.querySelector(".side-bar"), sidebarToggle=document.querySelector(".sidebar-toggle");
  if(toggle&&nav){toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");toggle.setAttribute("aria-expanded","false");}));}
  if(sidebarToggle&&sidebar){const adminLink=sidebar.querySelector('a[href="#admin"]');if(adminLink)adminLink.href="admin.html";sidebarToggle.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");sidebarToggle.setAttribute("aria-expanded",String(open));});sidebar.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{sidebar.classList.remove("open");sidebarToggle.setAttribute("aria-expanded","false");}));}
  const year=document.getElementById("year"); if(year)year.textContent=new Date().getFullYear();
  const filters=document.querySelectorAll(".filter"),cards=document.querySelectorAll(".service-card[data-category]");
  filters.forEach(f=>f.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));f.classList.add("active");const w=f.dataset.filter;cards.forEach(c=>c.classList.toggle("hidden",!(w==="all"||c.dataset.category===w||c.dataset.category==="all")));}));
  const serviceSelect=document.getElementById("service-select"),selected=document.getElementById("selected-service"),serviceForm=document.getElementById("service-request");
  const actionInput=serviceForm?Object.assign(document.createElement("input"),{type:"hidden",name:"request_action",value:"service"}):null;if(serviceForm&&actionInput)serviceForm.appendChild(actionInput);
  document.querySelectorAll(".service-action").forEach(b=>b.addEventListener("click",()=>{const s=b.dataset.service||"",label=(b.textContent||"").toLowerCase();if(serviceSelect)serviceSelect.value=s;if(selected)selected.value=s;if(actionInput)actionInput.value=label.includes("quote")?"quote":label.includes("order")?"order":"service";document.getElementById("start")?.scrollIntoView({behavior:"smooth"});setTimeout(()=>serviceSelect?.focus(),450);}));
  serviceSelect?.addEventListener("change",()=>{if(selected)selected.value=serviceSelect.value;});
  const API_BASE=(window.SSHP_API_BASE||"/api").replace(/\/$/,"");
  const endpointFor=(type,action)=>type==="Service Request"?(action==="quote"?"/quotes":action==="order"?"/orders":"/service-requests"):( {"Teacher Career Interest":"/teacher-interests","Private School Requirement":"/school-requirements","Community Content Contribution":"/content-submissions","Content Contribution":"/content-submissions"}[type]||"/submissions");
  async function post(path,payload){const r=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let j={};try{j=await r.json();}catch{}if(!r.ok)throw new Error((j.error||"The server could not process the request.")+(Array.isArray(j.details)?` ${j.details.join("; ")}`:""));return j;}
  document.querySelectorAll(".interaction-form").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();const msg=form.querySelector(".form-message"),type=form.dataset.type||"Website Form",data=Object.fromEntries(new FormData(form).entries());if(msg)msg.textContent="Submitting securely…";try{let payload=data;if(type==="Service Request"&&(data.request_action==="quote"||data.request_action==="order"))payload={service:data.service_select,name:data.name,phone:data.phone,email:data.email,requirement:data.requirement,request_action:data.request_action};const r=await post(endpointFor(type,data.request_action||"service"),type==="Website Form"?{type,data:payload}:payload);if(msg)msg.textContent=r.message||"Your request has been received successfully.";form.reset();if(selected)selected.value="";if(actionInput)actionInput.value="service";}catch(err){if(msg){msg.textContent=`Unable to submit right now. ${err.message}`;msg.setAttribute("data-error","true");}}}));

  const main=document.querySelector("main");
  if(main&&!document.getElementById("payments")){
    main.insertAdjacentHTML("beforeend",`<section class="section payment-section" id="payments"><div class="container payment-layout"><div class="payment-info"><span class="eyebrow">04 · PAYMENTS</span><h2>Submit an Omni payment reference.</h2><p>Use this experimental payment pathway after placing an order. The Hub will verify the transaction before the order is marked paid.</p><ul><li>Payment method: Omni</li><li>Enter the transaction/reference number exactly as issued.</li><li>Keep your payment receipt until verification is complete.</li></ul><p class="security-note">Never enter your PIN, password, OTP or other confidential banking credentials here.</p></div><form class="payment-form card-form" novalidate><label>Order ID <input name="order_id" required maxlength="100" autocomplete="off" placeholder="Enter your order ID"></label><label>Payment Method <select id="payment-method" name="method" required><option value="">Select payment method</option><option value="omni">Omni</option></select></label><div id="omni-fields"><label>Transaction / Reference Number <input name="transaction_reference" required maxlength="120" autocomplete="off" placeholder="Omni transaction reference"></label><div class="two-col"><label>Sender Name <input name="sender_name" required maxlength="120"></label><label>Sender Phone <input name="sender_phone" required maxlength="30" inputmode="tel"></label></div><div class="two-col"><label>Amount (PKR) <input name="amount_minor" type="number" min="1" step="1" required inputmode="numeric"></label><label>Currency <input name="currency" value="PKR" maxlength="3" pattern="[A-Za-z]{3}" required></label></div><label>Notes (optional) <textarea name="notes" rows="3" maxlength="500" placeholder="Optional payment note"></textarea></div><button class="btn btn-primary" type="submit">Submit Payment Reference →</button><p class="form-message payment-status" role="status" aria-live="polite"></p></form></div></section>`);
  }

  const pm=document.getElementById("payment-method"),of=document.getElementById("omni-fields");
  pm?.addEventListener("change",()=>{if(of)of.hidden=pm.value!=="omni";});
  if(of&&pm&&pm.value!=="omni")of.hidden=true;
  const pf=document.querySelector(".payment-form");pf?.addEventListener("submit",async e=>{e.preventDefault();const msg=pf.querySelector(".form-message"),data=Object.fromEntries(new FormData(pf).entries());if(msg){msg.textContent="Submitting payment reference securely…";msg.removeAttribute("data-error");}try{data.currency=String(data.currency||"").toUpperCase();data.amount_minor=Number(data.amount_minor);const r=await post("/payments",data);if(msg)msg.textContent=r.message||"Payment reference received for administrator verification.";pf.reset();if(of)of.hidden=true;}catch(err){if(msg){msg.textContent=`Unable to submit right now. ${err.message}`;msg.setAttribute("data-error","true");}}});
  const sections=[...document.querySelectorAll("main section[id]")],links=[...document.querySelectorAll(".main-nav a,.side-bar a")];
  if("IntersectionObserver"in window){const ob=new IntersectionObserver(es=>{const v=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+v.target.id));},{rootMargin:"-35% 0px -55% 0px",threshold:[0,.2,.5]});sections.forEach(s=>ob.observe(s));}
});
