document.addEventListener("DOMContentLoaded", () => {
  const toggle=document.querySelector(".menu-toggle"), nav=document.querySelector(".main-nav"), sidebar=document.querySelector(".side-bar"), sidebarToggle=document.querySelector(".sidebar-toggle");
  if(toggle&&nav){toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");toggle.setAttribute("aria-expanded","false");}));}
  if(sidebarToggle&&sidebar){sidebarToggle.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");sidebarToggle.setAttribute("aria-expanded",String(open));});sidebar.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{sidebar.classList.remove("open");sidebarToggle.setAttribute("aria-expanded","false");}));}
  const year=document.getElementById("year"); if(year)year.textContent=new Date().getFullYear();
  const filters=document.querySelectorAll(".filter"),cards=document.querySelectorAll(".service-card[data-category]");
  filters.forEach(f=>f.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));f.classList.add("active");const w=f.dataset.filter;cards.forEach(c=>c.classList.toggle("hidden",!(w==="all"||c.dataset.category===w||c.dataset.category==="all")));}));
  const serviceSelect=document.getElementById("service-select"),selected=document.getElementById("selected-service"),serviceForm=document.getElementById("service-request");
  const actionInput=serviceForm?Object.assign(document.createElement("input"),{type:"hidden",name:"request_action",value:"service"}):null;if(serviceForm&&actionInput)serviceForm.appendChild(actionInput);
  document.querySelectorAll(".service-action").forEach(b=>b.addEventListener("click",()=>{const s=b.dataset.service||"",label=(b.textContent||"").toLowerCase();if(serviceSelect)serviceSelect.value=s;if(selected)selected.value=s;if(actionInput)actionInput.value=label.includes("quote")?"quote":label.includes("order")?"order":"service";document.getElementById("start")?.scrollIntoView({behavior:"smooth"});setTimeout(()=>serviceSelect?.focus(),450);}));
  serviceSelect?.addEventListener("change",()=>{if(selected)selected.value=serviceSelect.value;});
  const API_BASE=(window.SSHP_API_BASE||"/api").replace(/\/$/,"");
  const endpointFor=(type,action)=>type==="Service Request"?(action==="quote"?"/quotes":action==="order"?"/orders":"/service-requests"):({"Teacher Career Interest":"/teacher-interests","Private School Requirement":"/school-requirements","Community Content Contribution":"/content-submissions","Content Contribution":"/content-submissions"}[type]||"/submissions");
  async function post(path,payload){const r=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let j={};try{j=await r.json();}catch{}if(!r.ok)throw new Error((j.error||"The server could not process the request.")+(Array.isArray(j.details)?` ${j.details.join("; ")}`:""));return j;}
  document.querySelectorAll(".interaction-form").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();const msg=form.querySelector(".form-message"),type=form.dataset.type||"Website Form",data=Object.fromEntries(new FormData(form).entries());if(msg)msg.textContent="Submitting securely…";try{let payload=data;if(type==="Service Request"&&(data.request_action==="quote"||data.request_action==="order"))payload={service:data.service_select,name:data.name,phone:data.phone,email:data.email,requirement:data.requirement,request_action:data.request_action};const r=await post(endpointFor(type,data.request_action||"service"),type==="Website Form"?{type,data:payload}:payload);if(msg)msg.textContent=r.message||"Your request has been received successfully.";form.reset();if(selected)selected.value="";if(actionInput)actionInput.value="service";}catch(err){if(msg){msg.textContent=`Unable to submit right now. ${err.message}`;msg.setAttribute("data-error","true");}}}));
  const pm=document.getElementById("payment-method"),of=document.getElementById("omni-fields");pm?.addEventListener("change",()=>{if(of)of.hidden=pm.value!=="omni";});
  const pf=document.querySelector(".payment-form");pf?.addEventListener("submit",async e=>{e.preventDefault();const msg=pf.querySelector(".form-message"),data=Object.fromEntries(new FormData(pf).entries());if(msg)msg.textContent="Submitting payment reference securely…";try{const r=await post("/payments",data);if(msg)msg.textContent=r.message||"Payment reference received for administrator verification.";pf.reset();if(of)of.hidden=true;}catch(err){if(msg){msg.textContent=`Unable to submit right now. ${err.message}`;msg.setAttribute("data-error","true");}}});
  const sections=[...document.querySelectorAll("main section[id]")],links=[...document.querySelectorAll(".main-nav a,.side-bar a")];
  if("IntersectionObserver"in window){const ob=new IntersectionObserver(es=>{const v=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+v.target.id));},{rootMargin:"-35% 0px -55% 0px",threshold:[0,.2,.5]});sections.forEach(s=>ob.observe(s));}
});
