<?php
declare(strict_types=1);

/* SSHP production API: PHP 8.x + MySQL/MariaDB. Same-origin /api/* endpoints. */
function envv(string $key, ?string $default=null): ?string { $v=getenv($key); return ($v===false||$v==='')?$default:$v; }
$configFile=__DIR__.'/config.php';
if(is_file($configFile)){ $loaded=require $configFile; if(is_array($loaded)) $GLOBALS['sshp_config']=$loaded; }
$GLOBALS['sshp_config']=array_merge([
 'db_host'=>envv('DB_HOST','localhost'),'db_port'=>envv('DB_PORT','3306'),'db_name'=>envv('DB_NAME',''),'db_user'=>envv('DB_USER',''),'db_pass'=>envv('DB_PASS',''),
 'admin_username'=>envv('ADMIN_USERNAME','admin'),'admin_password_hash'=>envv('ADMIN_PASSWORD_HASH',''),'session_ttl'=>(int)envv('SESSION_TTL_SECONDS','28800'),
 'rate_limit'=>(int)envv('RATE_LIMIT_MAX','60'),'rate_window'=>(int)envv('RATE_LIMIT_WINDOW_SECONDS','60'),'cors_origin'=>envv('CORS_ORIGIN','')
],$GLOBALS['sshp_config']??[]);
function cfg(string $key):mixed{return $GLOBALS['sshp_config'][$key]??null;}
function jsonResponse(int $status,array $payload):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');$origin=(string)cfg('cors_origin');$requestOrigin=$_SERVER['HTTP_ORIGIN']??'';if($origin!==''&&$requestOrigin===$origin){header('Access-Control-Allow-Origin: '.$origin);header('Access-Control-Allow-Methods: GET, POST, PATCH, OPTIONS');header('Access-Control-Allow-Headers: Content-Type, Authorization');header('Vary: Origin');}echo json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(($_SERVER['REQUEST_METHOD']??'GET')==='OPTIONS'){http_response_code(204);exit;}
function requestPath():string{$uri=parse_url($_SERVER['REQUEST_URI']??'/api',PHP_URL_PATH)?:'/api';$prefix=rtrim(dirname($_SERVER['SCRIPT_NAME']??'/api/index.php'),'/');if($prefix&&$prefix!=='/'&&str_starts_with($uri,$prefix))$uri=substr($uri,strlen($prefix));return'/'.ltrim((string)$uri,'/');}
function body():array{$raw=file_get_contents('php://input')?:'';if(strlen($raw)>1048576)jsonResponse(413,['success'=>false,'error'=>'Request body too large']);if($raw==='')return[];$d=json_decode($raw,true);if(!is_array($d))jsonResponse(400,['success'=>false,'error'=>'Invalid JSON']);return$d;}
function clean(mixed $v):mixed{if(is_array($v)){$o=[];foreach($v as$k=>$x)$o[(string)$k]=clean($x);return$o;}return is_string($v)?trim($v):$v;}
function id():string{return bin2hex(random_bytes(16));}function now():string{return gmdate('Y-m-d H:i:s');}function iso(string $d):string{return gmdate('c',strtotime($d));}
function clientIp():string{$f=$_SERVER['HTTP_X_FORWARDED_FOR']??'';return$f!==''?trim(explode(',',$f)[0]):($_SERVER['REMOTE_ADDR']??'unknown');}
function rateLimit():void{$max=(int)cfg('rate_limit');$window=(int)cfg('rate_window');if($max<=0||$window<=0)return;$file=sys_get_temp_dir().'/sshp_rl_'.hash('sha256',clientIp());$fp=@fopen($file,'c+');if(!$fp)return;flock($fp,LOCK_EX);$d=json_decode(stream_get_contents($fp)?:'',true)?:['start'=>time(),'count'=>0];if(time()-(int)$d['start']>=$window)$d=['start'=>time(),'count'=>0];$d['count']++;ftruncate($fp,0);rewind($fp);fwrite($fp,json_encode($d));fflush($fp);flock($fp,LOCK_UN);fclose($fp);if($d['count']>$max)jsonResponse(429,['success'=>false,'error'=>'Too many requests']);}rateLimit();
try{$dsn='mysql:host='.cfg('db_host').';port='.cfg('db_port').';dbname='.cfg('db_name').';charset=utf8mb4';$pdo=new PDO($dsn,(string)cfg('db_user'),(string)cfg('db_pass'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}catch(Throwable $e){error_log('SSHP DB connection failed: '.$e->getMessage());jsonResponse(500,['success'=>false,'error'=>'Database connection is not configured or unavailable.']);}
$services=[['id'=>'school-documentation','name'=>'School Documentation','category'=>'documents'],['id'=>'educational-forms-templates','name'=>'Educational Forms & Templates','category'=>'documents'],['id'=>'educational-design','name'=>'Educational Design','category'=>'design'],['id'=>'digital-online-support','name'=>'Digital & Online Support','category'=>'design'],['id'=>'school-support-services','name'=>'School Support Services','category'=>'school'],['id'=>'career-support','name'=>'Career Support','category'=>'career'],['id'=>'educational-content','name'=>'Educational Content','category'=>'documents'],['id'=>'custom-service-request','name'=>'Custom Service Request','category'=>'custom']];
$collections=['serviceRequests'=>'service_requests','teacherInterests'=>'teacher_interests','schoolRequirements'=>'school_requirements','contentSubmissions'=>'content_submissions','submissions'=>'submissions','quotes'=>'quotes','orders'=>'orders','payments'=>'payments','announcements'=>'announcements','resources'=>'resources','notifications'=>'notifications','auditLog'=>'audit_log'];
$columns=['service_requests'=>['id','service','name','phone','email','requirement','action','status','created_at','updated_at'],'teacher_interests'=>['id','name','phone','qualification','subject','opportunity','details','status','created_at','updated_at'],'school_requirements'=>['id','school','contact','phone','location','type','details','status','created_at','updated_at'],'content_submissions'=>['id','title','category','description','name','email','phone','status','created_at','updated_at'],'submissions'=>['id','type','data','status','created_at','updated_at'],'quotes'=>['id','service_request_id','customer_name','phone','email','service','amount_minor','currency','notes','status','created_at','updated_at'],'orders'=>['id','quote_id','customer_name','phone','email','service','amount_minor','currency','status','created_at','updated_at'],'payments'=>['id','order_id','method','transaction_reference','sender_name','sender_phone','amount_minor','currency','status','notes','created_at','updated_at'],'announcements'=>['id','title','category','description','status','created_at','updated_at'],'resources'=>['id','title','category','description','status','created_at','updated_at'],'notifications'=>['id','type','title','message','recipient','entity_id','read_flag','created_at'],'audit_log'=>['id','action','entity_id','type','actor','metadata','created_at']];
function tableFor(string $c):?string{global $collections;return $collections[$c]??null;}
function rowOut(string $t,array $r):array{$map=['created_at'=>'createdAt','updated_at'=>'updatedAt','service_request_id'=>'serviceRequestId','customer_name'=>'customerName','quote_id'=>'quoteId','order_id'=>'orderId','transaction_reference'=>'transactionReference','sender_name'=>'senderName','sender_phone'=>'senderPhone','entity_id'=>'entityId','read_flag'=>'read'];$o=[];foreach($r as$k=>$v){$key=$map[$k]??$k;if($k==='data'||$k==='metadata')$v=json_decode((string)$v,true)??[];if($k==='read_flag')$v=(bool)$v;if(($k==='created_at'||$k==='updated_at')&&$v)$v=iso((string)$v);$o[$key]=$v;}return$o;}
function listCollection(PDO $p,string $c,int $limit=200):array{$t=tableFor($c);if(!$t)return[];$s=$p->query("SELECT * FROM `$t` ORDER BY created_at DESC LIMIT ".max(1,min(500,$limit)));return array_map(fn($r)=>rowOut($t,$r),$s->fetchAll());}
function insertRow(PDO $p,string $c,array $r):void{global $columns;$t=tableFor($c);if(!$t)throw new RuntimeException('Unknown collection');$allowed=$columns[$t]??[];$d=[];foreach($r as$k=>$v){$k=str_replace('createdAt','created_at',str_replace('updatedAt','updated_at',$k));if(in_array($k,$allowed,true))$d[$k]=is_array($v)?json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):$v;}$n=array_keys($d);$m=array_map(fn($x)=>':'.$x,$n);$s=$p->prepare("INSERT INTO `$t` (`".implode('`,`',$n)."`) VALUES (".implode(',',$m).")");$s->execute(array_combine($m,array_values($d)));}
function authUser(PDO $p):?array{$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/^Bearer\s+(.+)$/i',$h,$m))return null;$token=$m[1];$s=$p->prepare('SELECT username,role,expires_at FROM sessions WHERE id=? AND expires_at>? LIMIT 1');$s->execute([hash('sha256',$token),time()]);$r=$s->fetch();return$r?['token'=>$token,'username'=>$r['username'],'role'=>$r['role'],'expiresAt'=>(int)$r['expires_at']]:null;}
function requireAdmin(PDO $p):array{$u=authUser($p);if(!$u)jsonResponse(401,['success'=>false,'error'=>'Administrator authentication required']);return$u;}
function notify(PDO $p,string $type,string $title,string $message,?string $entityId=null):void{insertRow($p,'notifications',['id'=>id(),'type'=>$type,'title'=>$title,'message'=>$message,'recipient'=>'admin','entity_id'=>$entityId,'read_flag'=>0,'created_at'=>now()]);}
function audit(PDO $p,string $action,?string $entityId,?string $type,?string $actor=null,array $metadata=[]):void{insertRow($p,'auditLog',['id'=>id(),'action'=>$action,'entityId'=>$entityId,'type'=>$type,'actor'=>$actor,'metadata'=>$metadata,'createdAt'=>now()]);}
$method=$_SERVER['REQUEST_METHOD'];$path=requestPath();
try{
if($method==='GET'&&$path==='/health')jsonResponse(200,['success'=>true,'service'=>'SCHOOLS SOLUTIONS HUB PAKISTAN API','status'=>'ok','version'=>'1.0.0','persistence'=>'mysql','timestamp'=>gmdate('c')]);
if($method==='GET'&&$path==='/services')jsonResponse(200,['success'=>true,'data'=>$services]);
if($method==='POST'&&$path==='/auth/login'){$b=clean(body());$ok=(string)($b['username']??'')===(string)cfg('admin_username')&&is_string($b['password']??null)&&(string)cfg('admin_password_hash')!==''&&password_verify($b['password'],(string)cfg('admin_password_hash'));if(!$ok)jsonResponse(401,['success'=>false,'error'=>'Invalid administrator credentials or authentication is not configured.']);$token=bin2hex(random_bytes(32));$expires=time()+(int)cfg('session_ttl');$pdo->prepare('DELETE FROM sessions WHERE expires_at<=?')->execute([time()]);$pdo->prepare('INSERT INTO sessions (id,username,role,expires_at,created_at) VALUES (?,?,?,?,?)')->execute([hash('sha256',$token),cfg('admin_username'),'admin',$expires,now()]);jsonResponse(200,['success'=>true,'data'=>['token'=>$token,'expiresAt'=>gmdate('c',$expires),'user'=>['username'=>cfg('admin_username'),'role'=>'admin']]]);}
if($method==='POST'&&$path==='/auth/logout'){$u=authUser($pdo);if($u)$pdo->prepare('DELETE FROM sessions WHERE id=?')->execute([hash('sha256',$u['token'])]);jsonResponse(200,['success'=>true]);}
if($method==='GET'&&$path==='/auth/me'){$u=authUser($pdo);if(!$u)jsonResponse(401,['success'=>false,'error'=>'Authentication required']);jsonResponse(200,['success'=>true,'data'=>['username'=>$u['username'],'role'=>$u['role'],'expiresAt'=>gmdate('c',$u['expiresAt'])]]);}
if($method==='GET'&&($path==='/resources'||$path==='/announcements')){$c=$path==='/resources'?'resources':'announcements';jsonResponse(200,['success'=>true,'data'=>listCollection($pdo,$c,200)]);}
if(str_starts_with($path,'/admin/')){$u=requireAdmin($pdo);if($method==='GET'&&$path==='/admin/dashboard'){$counts=[];foreach($collections as$c=>$t)$counts[$c]=(int)$pdo->query("SELECT COUNT(*) FROM `$t`")->fetchColumn();jsonResponse(200,['success'=>true,'data'=>['counts'=>$counts,'generatedAt'=>gmdate('c')]]);}if($method==='GET'&&$path==='/admin/notifications')jsonResponse(200,['success'=>true,'data'=>listCollection($pdo,'notifications',100)]);if($method==='GET'&&preg_match('#^/admin/collections/([A-Za-z0-9_-]+)$#',$path,$m)&&isset($collections[$m[1]]))jsonResponse(200,['success'=>true,'data'=>listCollection($pdo,$m[1],200)]);if($method==='PATCH'&&preg_match('#^/admin/collections/([A-Za-z0-9_-]+)/([^/]+)$#',$path,$m)&&isset($collections[$m[1]])){$collection=$m[1];$table=tableFor($collection);global $columns;$b=clean(body());$allowed=['status','read','notes','assignedTo','amount_minor','currency','title','description','category'];$data=[];foreach($b as$k=>$v)if(in_array($k,$allowed,true))$data[$k]=$v;$rename=['assignedTo'=>'assigned_to','read'=>'read_flag'];foreach($data as$k=>$v)if(isset($rename[$k])){$data[$rename[$k]]=$v;unset($data[$k]);}$valid=$columns[$table]??[];$data=array_filter($data,fn($v,$k)=>in_array($k,$valid,true),ARRAY_FILTER_USE_BOTH);if(!$data)jsonResponse(422,['success'=>false,'error'=>'No permitted fields supplied']);$sets=[];$params=[];foreach($data as$k=>$v){$sets[]="`$k`=?";$params[]=$v;}$params[]=$m[2];$s=$pdo->prepare("UPDATE `$table` SET ".implode(',',$sets)." WHERE id=?");$s->execute($params);if(!$s->rowCount())jsonResponse(404,['success'=>false,'error'=>'Record not found']);$q=$pdo->prepare("SELECT * FROM `$table` WHERE id=?");$q->execute([$m[2]]);$row=$q->fetch();audit($pdo,'admin.record.updated',$m[2],$collection,$u['username'],$data);jsonResponse(200,['success'=>true,'data'=>rowOut($table,$row)]);}}
if($method==='POST'){
$routes=['/service-requests'=>['Service Request','serviceRequests'],'/teacher-interests'=>['Teacher Career Interest','teacherInterests'],'/school-requirements'=>['Private School Requirement','schoolRequirements'],'/content-submissions'=>['Community Content Contribution','contentSubmissions'],'/submissions'=>[null,'submissions']];
if(isset($routes[$path])){$type=$routes[$path][0];$collection=$routes[$path][1];$b=clean(body());$data=$type?$b:($b['data']??[]);$data=is_array($data)?$data:[];if($type==='Service Request'&&isset($data['service_select'])&&!isset($data['service']))$data['service']=$data['service_select'];$required=$type==='Service Request'?['service_select','name','phone','requirement']:($type==='Teacher Career Interest'?['name','phone','qualification','subject','opportunity']:($type==='Private School Requirement'?['school','contact','phone','location','type','details']:[]));$errors=[];foreach($required as$f)if(($data[$f]??'')==='')$errors[]="$f is required";if(isset($data['email'])&&$data['email']!==''&&!filter_var($data['email'],FILTER_VALIDATE_EMAIL))$errors[]='email is invalid';if(isset($data['phone'])&&$data['phone']!==''&&!preg_match('/^[+()\-\s\d]{7,40}$/',(string)$data['phone']))$errors[]='phone is invalid';if($errors)jsonResponse(422,['success'=>false,'error'=>'Validation failed','details'=>$errors]);$rid=id();$created=now();if($type){$row=['id'=>$rid]+$data+['status'=>'received','createdAt'=>$created];if($collection==='contentSubmissions'){$row['category']=$data['content_type']??$data['category']??null;$row['description']=$data['details']??$data['description']??null;}if($collection==='serviceRequests'){$row['action']=$data['request_action']??$data['action']??'service';unset($row['service_select'],$row['request_action']);}}else{$row=['id'=>$rid,'type'=>(string)($b['type']??'Website Form'),'data'=>$data,'status'=>'received','createdAt'=>$created];}insertRow($pdo,$collection,$row);audit($pdo,'submission.received',$rid,$row['type']??$type);notify($pdo,'new-submission','New website submission',($row['type']??$type).' received from '.($data['name']??$data['school']??'website user').'.',$rid);jsonResponse(201,['success'=>true,'message'=>'Submission received successfully.','data'=>['id'=>$rid,'status'=>'received','createdAt'=>iso($created)]]);}
if($path==='/quotes'||$path==='/orders'){$b=clean(body());$errors=[];foreach(['service','name','phone']as$f)if(($b[$f]??'')==='')$errors[]="$f is required";if(isset($b['email'])&&$b['email']!==''&&!filter_var($b['email'],FILTER_VALIDATE_EMAIL))$errors[]='email is invalid';if($errors)jsonResponse(422,['success'=>false,'error'=>'Validation failed','details'=>$errors]);$c=$path==='/quotes'?'quotes':'orders';$row=['id'=>id(),'service'=>$b['service'],'customer_name'=>$b['name'],'phone'=>$b['phone'],'email'=>$b['email']??null,'amount_minor'=>$b['amount_minor']??null,'currency'=>$b['currency']??'PKR','status'=>$c==='quotes'?'requested':'pending','createdAt'=>now()];if($c==='quotes'){$row['service_request_id']=$b['service_request_id']??null;$row['notes']=$b['requirement']??$b['notes']??null;}else{$row['quote_id']=$b['quote_id']??null;}insertRow($pdo,$c,$row);notify($pdo,$c==='quotes'?'new-quote':'new-order',$c==='quotes'?'New quote request':'New service order',($c==='quotes'?'Quote':'Order').' received for '.$b['service'].'.',$row['id']);jsonResponse(201,['success'=>true,'message'=>$c==='quotes'?'Quote request received successfully.':'Order received successfully.','data'=>rowOut(tableFor($c),$row)]);}
if($path==='/payments'){$b=clean(body());$errors=[];foreach(['order_id','method','transaction_reference','sender_name','sender_phone','amount_minor','currency']as$f)if(($b[$f]??'')==='')$errors[]="$f is required";if(($b['method']??'')!=='omni')$errors[]='Only the Omni payment method is currently supported';if(isset($b['amount_minor'])&&(!is_numeric($b['amount_minor'])||(float)$b['amount_minor']<=0))$errors[]='amount_minor must be positive';if(isset($b['currency'])&&strlen((string)$b['currency'])!==3)$errors[]='currency must be a 3-letter code';if($errors)jsonResponse(422,['success'=>false,'error'=>'Validation failed','details'=>$errors]);$row=['id'=>id(),'order_id'=>$b['order_id'],'method'=>'omni','transaction_reference'=>$b['transaction_reference'],'sender_name'=>$b['sender_name'],'sender_phone'=>$b['sender_phone'],'amount_minor'=>(int)$b['amount_minor'],'currency'=>strtoupper((string)$b['currency']),'status'=>'pending_verification','notes'=>$b['notes']??null,'createdAt'=>now()];insertRow($pdo,'payments',$row);audit($pdo,'payment.reference.submitted',$row['id'],'payments');notify($pdo,'payment-reference','New Omni payment reference','Omni payment reference submitted for order '.$b['order_id'].'.',$row['id']);jsonResponse(201,['success'=>true,'message'=>'Payment reference received. The Hub will verify it before the order is marked paid.','data'=>['id'=>$row['id'],'status'=>$row['status']]]);}
}
jsonResponse(404,['success'=>false,'error'=>'Route not found']);
}catch(Throwable $e){error_log('SSHP API error: '.$e->getMessage());jsonResponse(500,['success'=>false,'error'=>'Internal server error']);}
